# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: provider
services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5433:5433
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=bsuser
